name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: macOS (Xcode ${{ matrix.xcode }})
    runs-on: macos-14
    strategy:
      matrix:
        xcode:
          - '15.4'
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Print Swift version
        run: swift --version
      - name: Run tests
        run: make test-swift

  linux:
    strategy:
      matrix:
        swift:
          - '5.10'
    name: Ubuntu (Swift ${{ matrix.swift }})
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test --parallel
      - name: Run tests (release)
        run: swift test -c release --parallel

  wasm:
    name: SwiftWasm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - wasm-DEVELOPMENT-SNAPSHOT-2024-07-16-a
    steps:
      - name: Cache toolchains
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Toolchains
          key: ${{ matrix.toolchain }}
      - uses: actions/checkout@v4
      - uses: bytecodealliance/actions/wasmtime/setup@v1
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: ${{ matrix.toolchain }}
      - name: Build tests
        run: swift build --triple wasm32-unknown-wasi --build-tests -Xlinker -z -Xlinker stack-size=$((1024 * 1024))
      - name: Run tests
        run: wasmtime .build/debug/swift-case-pathsPackageTests.wasm

  # windows:
  #   name: Windows (Swift ${{ matrix.swift }}, ${{ matrix.config }})
  #   strategy:
  #     matrix:
  #       os: [windows-latest]
  #       config:
  #         - debug
  #         #- release
  #       swift: ['6.0']
  #     fail-fast: false
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: compnerd/gha-setup-swift@main
  #       with:
  #         branch: swift-${{ matrix.swift }}-branch
  #         tag: ${{ matrix.swift }}-DEVELOPMENT-SNAPSHOT-2024-06-03-a
  #     - uses: actions/checkout@v4
  #     - name: Build
  #       run: swift build -c ${{ matrix.config }}
